In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [6]:
df.sample(5)

     sepal_length  sepal_width  petal_length  petal_width  species
92            5.8          2.6           4.0          1.2        1
8             4.4          2.9           1.4          0.2        0
142           5.8          2.7           5.1          1.9        2
95            5.7          3.0           4.2          1.2        1
53            5.5          2.3           4.0          1.3        1

In [7]:
df = df[['sepal_length','petal_length','species']]

In [9]:
df.sample(5)

     sepal_length  petal_length  species
63            6.1           4.7        1
121           5.6           4.9        2
107           7.3           6.3        2
96            5.7           4.2        1
71            6.1           4.0        1

In [10]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [12]:
X_train.head()

     sepal_length  petal_length
126           6.2           4.8
23            5.1           1.7
64            5.6           3.6
117           7.7           6.7
84            5.4           4.5

In [13]:
clf = LogisticRegression(multi_class='multinomial')

In [14]:
clf.fit(X_train,y_train)

c:\Users\zhass\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='multinomial')

In [15]:
y_pred = clf.predict(X_test)

In [16]:
print(f"accuracy_score : {accuracy_score(y_test,y_pred)}")

accuracy_score : 0.9666666666666667

In [17]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0  1  2
0  14  0  0
1   0  7  1
2   0  0  8