In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('play_tennis.csv')
df.head()
df.drop(columns='day' , inplace=True)

In [ ]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [7]:
df.shape

(14, 5)

In [28]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [29]:
py = 9/14
pn = 5/14

In [30]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

probability for outlook column

In [31]:
pd.crosstab(df['outlook'] , df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [34]:
Poulookn = 0/5
Prrainn = 2/5
Pssunnyn = 3/5

Poutlooky = 4/9
Prainy =3/9
Psunnyy = 2/9

probability for temperature column

In [33]:
pd.crosstab(df['temp'] ,df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [35]:
Pcoolno = 1/5
Photno = 2/5
Pmildno = 2/5


Pcoolyes = 3/9
photyes = 2/9
Pmildyes = 4/9

probability for humidity column

In [36]:
pd.crosstab(df['humidity'] ,df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [37]:
Phighno = 4/5
Pnormalno = 1/5

Phighyes = 3/9
pnormalyes = 6/9

probability for wind column

In [38]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [39]:
Pstrongno = 3/5
Pweakno = 2/5

Pstrongyes = 3/9
Pweakyes = 6/9

problem no 1 
outlook = sunny , temp = hot , humidity = high , wind = weak 
find probality of plyaing match for this problem

In [40]:
Pyes = py*Psunnyy*photyes*Phighyes*Pweakyes

In [41]:
Pyes

0.007054673721340388

In [42]:
Pno = pn*Pssunnyn*Photno*Phighno*Pweakno

In [43]:
Pno

0.02742857142857143

as Pno > Pyes so no game wil be played on this day